export const ACTIVITY_EVENT_TYPES = {
  RESUME_UPLOADED: 'RESUME_UPLOADED',
  RESUME_PARSED: 'RESUME_PARSED',
  RESUME_PARSE_FAILED: 'RESUME_PARSE_FAILED',

  RESUME_MATCH_UPDATED: 'RESUME_MATCH_UPDATED',
  RESUME_MATCH_FAILED: 'RESUME_MATCH_FAILED',

  LEARNING_PLAN_GENERATED: 'LEARNING_PLAN_GENERATED',
  LEARNING_PLAN_FAILED: 'LEARNING_PLAN_FAILED',

  JOB_APPLIED: 'JOB_APPLIED',

  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',
  JOB_LIFECYCLE_CHANGED: 'JOB_LIFECYCLE_CHANGED',
  JOB_DEADLINE_CHANGED: 'JOB_DEADLINE_CHANGED',

  JOB_POSTING_REVIEWED: 'JOB_POSTING_REVIEWED',

  RESUME_REGENERATED: 'RESUME_REGENERATED',
  RESUME_RENDER_FAILED: 'RESUME_RENDER_FAILED',

  RESUME_OUTDATED: 'RESUME_OUTDATED',

  MANUAL_RETRY_REQUESTED: 'MANUAL_RETRY_REQUESTED',
  TARGET_JOB_CHANGED: 'TARGET_JOB_CHANGED',
}

export const NOTIFICATION_DELIVERY_TYPES = {
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL',
}

export const JOB_TYPES = {
  RESUME_PARSING: 'RESUME_PARSING',
  RESUME_MATCHING: 'RESUME_MATCHING',
  LEARNING_PLAN: 'LEARNING_PLAN',
  RESUME_RENDERING: 'RESUME_RENDERING',
}

export const JOB_STATUS = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
}
